name: Discovery Service build and tests

on:
  pull_request:
    branches:
      - dev
      - main
    paths:
      - 'services/discovery-service/**'

  push:
    branches:
      - feature/**
      - dev
      - main
    paths:
      - 'services/discovery-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build
        run: mvn clean install

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('services/discovery-service/**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build and run tests
        run: mvn -f services/discovery-service/pom.xml clean verify

      - name: Run Checkstyle
        run: mvn -f services/discovery-service/pom.xml checkstyle:check
